apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    namespace: demoargo
spec:
  template:
    spec:
      containers:
      - name: presync-notification
        image: alpine:latest
        command: ["/bin/echo", "L’application est bien synchronisé dans l'état désiré."]
      restartPolicy: Never