apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    namespace: demoargo
spec:
  template:
    spec:
      containers:
      - name: presync-notification
        image: alpine:latest
        command: ["/bin/echo", "L’application sera synchronisé avec un nouvel état désiré."]
      restartPolicy: Never